### ISSUE TITLE
Motors getting stuck at constant speed

### ISSUE THREAD

**Issue by sfe-SparkFro** [bb-frc-workshops/xrp-wpilib#16]
Just after starting TeleOp, the motors are stationary like they should be. As soon as any PWM message is received, the motors appear to get stuck at their max speed, regardless of joystick values. If I comment out the `<position` case here (line 104-109), that fixes it:

https://github.com/bb-frc-workshops/xrp-wpilib/blob/00df9d3227b38fa09b7bb05a1edfd60c415c1d74/src/wpilibws_processor.cpp#L94-L110

After looking at the JSON packets being received, the [`<speed` and `<position` messages](https://github.com/wpilibsuite/allwpilib/blob/main/simulation/halsim_ws_core/doc/hardware_ws_api.md#pwm-output-pwm) are received separately. `<position` seems to always get set second, so I suspect it's overwriting the `<speed` value immediately.

I'd suggest choosing to use `<speed` or `<position` based on what makes more sense for the provided `device` number (eg. speed for motors and position for servos)

**Comment by zhiquanyeo** [comment]
Ah right! When I first wrote the code, there was a bug in WPILib that wouldn't set the position value properly (hence why early testing never saw this problem)
